schema_version = "1.0.0"
id = "send2ue"
name = "Send to Unreal"
tagline = "Send assets directly to an open Unreal Editor on your machine"
version = "2.6.0"
type = "add-on"
tags = [ "Pipeline" ]
blender_version_min = "4.2.0"
website = "https://poly-hammer.github.io/BlenderTools/send2ue"
maintainer = "JoshQuake, jack-yao91"
license = [ "SPDX:MIT" ]
copyright = [
    "2020-2023 Epic Games, Inc."
]

[permissions]
files = "Import/export FBX from/to disk"
